In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1:4]

array([1, 2, 3])

In [4]:
arr[:3]

array([0, 1, 2])

In [5]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[-4:-1]

array([7, 8, 9])

In [8]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [9]:
len(slice_of_arr)

6

In [10]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
arr  #Proves same copy for both is using

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_2d = np.array([[5,3,6],[6,8,7],[1,2,3]])
arr_2d

array([[5, 3, 6],
       [6, 8, 7],
       [1, 2, 3]])

In [16]:
arr_2d[:2,1:]

array([[3, 6],
       [8, 7]])

In [19]:
arr = np.arange(1,11)
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [27]:
(arr%2==0).any()

True

In [28]:
(arr%5==0).all()

False