In [1]:
list = [1,2,3,4]

In [2]:
import numpy as np

In [3]:
arr = np.array(list)
arr

array([1, 2, 3, 4])

In [4]:
mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [13]:
type(np.linspace(0,10,6))

numpy.ndarray

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.6533704 , 0.14666206, 0.5837365 , 0.86010484, 0.1239498 ])

In [16]:
np.random.rand(4,5)

array([[0.16394723, 0.52999327, 0.29143491, 0.6683914 , 0.51301795],
       [0.31200435, 0.33874319, 0.7284112 , 0.20168271, 0.21882346],
       [0.92179638, 0.92985019, 0.37968539, 0.80019792, 0.7432335 ],
       [0.26087576, 0.42509401, 0.50560075, 0.24576265, 0.16391349]])

In [18]:
np.random.randn(2)

array([ 0.91705551, -0.97627162])

In [19]:
np.random.randint(1,100) #Generate random b/w two numbers (last no. exclusive)

71

In [20]:
np.random.randint(1,100,10)

array([47, 74, 66, 11, 79, 16, 42, 61, 71, 77])

In [25]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)
ranarr

array([18, 17, 35, 23, 27,  6, 45, 26,  9,  4])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

45

In [28]:
ranarr.min()

4

In [29]:
ranarr.argmax()

6

In [30]:
ranarr.argmin()

9

In [31]:
arr.shape

(25,)

In [33]:
arr = arr.reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
arr.shape

(5, 5)

In [35]:
arr.dtype

dtype('int64')

In [36]:
ranarr.dtype

dtype('int64')